### ISSUE TITLE
Can't start on Linux

### ISSUE THREAD

**Issue by qubodup** [spajus/tank_island#2]
Hello,

I'm trying to run this on Linux but it fails

<pre>$ tank_island 
/home/qubodup/.gem/ruby/2.2.0/gems/tank_island-1.0.3/lib/entities/components/tank_health.rb:1:in `<top (required)>': uninitialized constant Health (NameError)
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/qubodup/.gem/ruby/2.2.0/gems/tank_island-1.0.3/bin/tank_island:24:in `block in <top (required)>'
	from /home/qubodup/.gem/ruby/2.2.0/gems/tank_island-1.0.3/bin/tank_island:23:in `each'
	from /home/qubodup/.gem/ruby/2.2.0/gems/tank_island-1.0.3/bin/tank_island:23:in `<top (required)>'
	from /home/qubodup/.gem/ruby/2.2.0/bin/tank_island:23:in `load'
	from /home/qubodup/.gem/ruby/2.2.0/bin/tank_island:23:in `<main>'</pre>

**Comment by spajus** [comment]
Hi, could you be more specific - which distribution and version?

**Comment by qubodup** [comment]
My bad!

Arch Linux rolling release, tank_island git HEAD.

gem list > http://codepad.org/WI6u86hv
pacman -Q > http://codepad.org/7LPN63Tg

I have no experience debugging ruby, so please pardon the briefness.

**Comment by spajus** [comment]
In your case, something does't work right with automatic require of all game files:

https://github.com/spajus/tank_island/blob/master/bin/tank_island#L7-L25

If you could try editing `which tank_island` and debugging what's going on, it would be helpful. Otherwise I'll install Arch Linux and try it myself, but it could take a while.

**Comment by spajus** [comment]
The class that is missing is located in lib/entities/components/health.rb, but on your system tank_health.rb takes precedence. The issue is clear, I'll fix this over the weekend. Thanks for reporting!

**Comment by spajus** [comment]
@qubodup I've updated the gem, please run `gem uninstall tank_island && gem install tank_island` and try to run the game.

**Comment by qubodup** [comment]
Thanks, it works now.

Video: http://youtu.be/c2M_zJ9KcS8

**Comment by spajus** [comment]
I linked to your video in README.md, it's certainly better than the one I made. I hope you don't mind. :)
